filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'
    - 'tools/'

# see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
build:
  dependencies:
    override:
      - composer update --no-interaction --no-dev
  nodes:
    php:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

tools:
  external_code_coverage: true
