language: php

# php compatibility
php: ["7.2", "7.3", "7.4snapshot"]

env:
  global:
    - FINKOK_SNID="SN03192650"
    - FINKOK_USERNAME="carlos.c.soto@flintgrp.com"
    - FINKOK_REGISTRATION_ADD_CREATE_RANDOM_RFC="1"
    - FINKOK_LOG_CALLS="0"
    - secure: "BGouECVCbSZ2LUtUrxHFkvIB4pn+7IHk+sp5hgX/baoEgOBhzasvNI/YVGCBYCAul0q1Af8WpJmFTwKrYY/fXZGcD4E5HN7yUF0MCQx9tDZrpIgOeSdiKGxUHU/ijkunDP11R5i4PMj8VB5uptOmjJmkxxjEf/Emz/YIA71MvB2LIjQWgE5XWpNkui0/XWtFih9/ZWEesJrrnWcddSHOQxYb2u2bg9yt4gq3snmaj71Mbw9nOHQy6zxxVbeS5DtLd3oLoxlM++C2xB59iiAaZv+unFFau7BNhfqYv9MerdhARtSmSXJY5jNOatZWzZx8hZe1kqG0Ar/GsctUxIpSX6MdDbl2Ewrheqhme1lWicBssKBA3UPyxaHuiIU9vcZD67sLKo079Dr4NjqV0e2raOZTjtNKMUcvPlj2X0GYFXnVfDIVaKxChZ+CaUXXS+ROVmYYMrv7yeFqLKGW/sLqBRSZ+6j/uBcXx9e6ryL7RpKLuykHAAnXKvXuksB4puvw2EYpR/XynCw//ZzhC9wq0oFhafHzU2NecOYT3OLGMQxS+/v2gZxjzbo7HRUX0aUBQmn2bJIPRlIf0BlWoy4tUc1+GBWjebQVdZc6NYM63hi+A9r9pXUlrs5Abx7F6QVgkxDHpWSRnAvkXhvMg42zaYNz2+jXxyTW0F9wRr1FHzE="
    - PHPUNIT_TEST_PATH=$( test -n "$FINKOK_PASSWORD" && echo -n tests/ || echo -n tests/Unit/ )

matrix:
  allow_failures:
    - php: "7.4snapshot"

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phplint
  - vendor/bin/php-cs-fixer fix --verbose
  - vendor/bin/phpcbf --colors -sp src/ tests/
  - phpdbg -qrr vendor/bin/phpunit --testdox --verbose --coverage-clover coverage.xml $PHPUNIT_TEST_PATH
  - vendor/bin/phpstan analyse --no-progress --verbose --level max src/ tests/

after_success:
  - |
    if [ -f "coverage.xml" ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
      echo "Scrutinizer code coverage upload status: $?"
    fi

notifications:
  email: false
