language: php

# php compatibility
php: ["7.3", "7.4", "8.0"]

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix --verbose
  - vendor/bin/phpcs --colors -sp src/ tests/
  - vendor/bin/phpunit --testdox --verbose tests/Unit/
  - vendor/bin/phpstan analyse --no-progress --verbose --level max src/ tests/

notifications:
  email: false
